[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ms2lipid"
version = "0.0.1"
authors = [
  { name="NamiSakamoto", email="123930464+NamiSakamoto@users.noreply.github.com" },
]
description = "a tool of predict lipid class by using ms2 spectrum"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pandas",
    "tensorflow",
    "keras",
]

[project.urls]
Homepage = "https://github.com/systemsomicslab/ms2lipid"
Issues = "https://github.com/systemsomicslab/ms2lipid/issues"
